---

services:   
  phpmyadmin:
    image: phpmyadmin:apache
    container_name: phpmyadmin
    restart: always
      
    networks:
      traefik_proxy:

    environment:
      - PMA_HOST=172.18.99.1
      - PMA_ABSOLUTE_URI=https://phpsql.datanen.vip

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.entrypoints=http,https"      
      - "traefik.http.routers.phpmyadmin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.phpmyadmin.tls=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpsql.datanen.vip`)"
      - "traefik.http.routers.phpmyadmin.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.phpmyadmin.middlewares=security-headers@docker"

networks:
  traefik_proxy:
    external: true
